### ISSUE TITLE
Scripts?

### ISSUE THREAD

**Issue by alexandre-mbm** [PoliticaColaborativa/ConstituicaoBrasileira#10]
@eduardocruz, você é o idealizador e o gerente deste projeto, por isso a pergunta.

Quais linguagens de programação viabillizariam scripts executáveis no sistema operacional que você usa? Se eu escrevesse _shell scripts_ (Bash), usando principalmente `grep`, `sed` e `awk`, isso poderia ser utilizado em seu sistema? Nunca usei Mac e não sei nem pra onde vai...

Outras linguagens que contemplo desde já: Ruby, Python.

Claro que os _scripts_ poderiam ser feitos para serem executados uma única vez (por mim) ou só por mim, mas prefiro fazer algo compartilhável com os demais. Penso em pequenos facilitadores para mudança de padrões, e em extratores de conteúdos de fontes TXT ou HTML.

**Comment by eduardocruz** [comment]
O Mac OS é baseado no Unix BSD, então dá pra pensar que o que roda no linux, roda nele. O shell é semelhante. Em relação a linguagens, ruby, python, todas rodam nele sem problema.
