### ISSUE TITLE
README.md da raiz é necessário?

### ISSUE THREAD

**Issue by alexandre-mbm** [PoliticaColaborativa/ConstituicaoBrasileira#8]
- [x] Testar se ele é usado pelo Gitbook (por exemplo, para a página de publicação/venda)

Se o arquivo for completamente ignorado no caso atual do livro internacioalizado, como passou a acontecer com o `/SUMMARY.md` que foi apagado, então a utilidade dele fica apenas para o GitHub e ele pode receber **instruções básicas sobre como interessados podem colaborar com o projeto**.

---
- [ ] `/README.md`: instruções básicas sobre como interessados podem colaborar com o projeto

**Comment by eduardocruz** [comment]
Sim, o readme.md da raiz é necessário. Incluída motivação do projeto e fechando a issue.
